var myString = "Hello, TypeScript!";
console.log(myString);
var myNumber = 38;
console.log(myNumber);
var myBoolean = true;
console.log(myBoolean);
var myNull = null;
console.log(myNull);
var myAny = "I can be anything!";
console.log(myAny);
myAny = 25;
console.log(myAny);
myAny = true;
console.log(myAny);
